#!/usr/bin/env python3
# ============================================================
# train_quick.py - Win11 RTX 4060 快速訓練腳本
# 訓練 YOLOv8-Nano 並導出 opset=12 ONNX
# 用於 JyTrainer Win7 C++ 部署
# ============================================================
import sys
import os
import shutil
import argparse
from pathlib import Path

def print_banner():
    print("=" * 50)
    print("  亂2 Online - YOLOv8 訓練腳本")
    print("  Win11 RTX 4060 專用版")
    print("=" * 50)

def check_requirements():
    """檢查必要套件"""
    print("\n[1/5] 檢查環境...")

    try:
        from ultralytics import YOLO
        print("    [OK] ultralytics")
    except ImportError:
        print("    [ERROR] 請先安裝: pip install ultralytics")
        return False

    try:
        import torch
        print(f"    [OK] PyTorch: {torch.__version__}")
        if torch.cuda.is_available():
            print(f"    [OK] CUDA: {torch.cuda.get_device_name(0)}")
        else:
            print("    [WARNING] 未檢測到 GPU，將使用 CPU 訓練（較慢）")
    except ImportError:
        print("    [ERROR] PyTorch 未安裝")
        return False

    return True

def prepare_data(data_path):
    """準備數據集"""
    print("\n[2/5] 準備數據集...")

    data_path = Path(data_path)
    if not data_path.exists():
        print(f"    [ERROR] 路徑不存在: {data_path}")
        return False

    images_dir = data_path / "images"
    labels_dir = data_path / "labels"

    if not images_dir.exists():
        print(f"    [ERROR] 缺少 images/ 目錄")
        return False
    if not labels_dir.exists():
        print(f"    [ERROR] 缺少 labels/ 目錄")
        return False

    # 統計
    image_files = list(images_dir.glob("*.jpg")) + list(images_dir.glob("*.png"))
    print(f"    [INFO] 找到 {len(image_files)} 張圖片")

    if len(image_files) < 10:
        print(f"    [WARNING] 樣本數量較少，建議至少 10 張")
    elif len(image_files) < 50:
        print(f"    [WARNING] 建議收集更多樣本以提高準確率")

    return True

def create_yaml(data_path, classes, project_dir):
    """創建 YOLO 配置"""
    print("\n[3/5] 創建訓練配置...")

    project_dir = Path(project_dir)
    project_dir.mkdir(exist_ok=True)

    # 類別格式化
    class_list = ", ".join(f"'{c}'" for c in classes)

    yaml_content = f"""# YOLOv8 Training Config
# Auto-generated by train_quick.py

path: {str(Path(data_path).resolve())}
train: images
val: images

nc: 1
names: ['monster']

# Training settings
epochs: 80
batch: 8
imgsz: 1280
device: 0  # 0 = GPU, 'cpu' = CPU
save: True
project: {project_dir.name}
name: yolov8_train
exist_ok: True
verbose: True
"""

    yaml_path = project_dir / "data.yaml"
    with open(yaml_path, "w", encoding="utf-8") as f:
        f.write(yaml_content)

    print(f"    [OK] 配置: {yaml_path}")
    return yaml_path

def train(data_yaml, model_size="n", epochs=100, batch=16):
    """訓練 YOLOv8"""
    print(f"\n[4/5] 訓練模型 ({model_size})...")

    from ultralytics import YOLO

    # 選擇模型
    model_map = {"n": "yolov8n", "s": "yolov8s", "m": "yolov8m"}
    model_name = model_map.get(model_size, "yolov8n")

    print(f"    [INFO] 模型: {model_name}")
    print(f"    [INFO] Epochs: {epochs}")
    print(f"    [INFO] Batch: {batch}")

    try:
        model = YOLO(f"{model_name}.pt")
    except:
        print(f"    [INFO] 使用預設配置訓練")
        model = YOLO(f"{model_name}.yaml")

    # 訓練
    results = model.train(
        data=str(data_yaml),
        epochs=epochs,
        batch=batch,
        imgsz=640,
        device=0,
        project="runs/train",
        name="jy_trainer",
        exist_ok=True,
        verbose=True,
        save=True,
        save_period=10,
    )

    return Path(results.save_dir) / "weights" / "best.pt"

def export_onnx(model_path, opset=12, simplify=True):
    """導出 ONNX（opset=12 for Win7 C++ OpenCV 4.5.5）"""
    print(f"\n[5/5] 導出 ONNX...")

    from ultralytics import YOLO

    print(f"    [INFO] 模型: {model_path}")
    print(f"    [INFO] Opset: {opset}")
    print(f"    [INFO] Simplify: {simplify}")

    model = YOLO(str(model_path))

    # 導出為 ONNX
    onnx_path = model.export(
        format="onnx",
        opset=opset,          # 關鍵：opset=12 兼容性最好
        simplify=simplify,    # 簡化模型
        dynamic=False,         # 固定尺寸加速
    )

    print(f"    [OK] ONNX 導出成功")
    return onnx_path

def copy_to_project(onnx_path, dest_name="best.onnx"):
    """複製到專案目錄"""
    project_models = Path(".") / "models"
    project_models.mkdir(exist_ok=True)

    dest = project_models / dest_name
    shutil.copy2(onnx_path, dest)

    print(f"\n[完成]")
    print(f"    [INFO] 模型位置: {dest}")
    print(f"    [INFO] 複製到專案 models/ 目錄")
    print(f"\n使用方式：")
    print(f"    1. 將 {dest} 複製到 JyTrainer.exe 同目錄")
    print(f"    2. 確保目錄中有 best.onnx")
    print(f"    3. 執行 JyTrainer.exe")

    return dest

def main():
    parser = argparse.ArgumentParser(description="快速訓練 YOLOv8")
    parser.add_argument("--data", "-d", default="training_data",
                       help="訓練數據目錄")
    parser.add_argument("--classes", "-c", nargs="+",
                       default=["monster", "player", "npc", "npc_shop"],
                       help="類別名稱")
    parser.add_argument("--epochs", "-e", type=int, default=100,
                       help="訓練輪數")
    parser.add_argument("--batch", "-b", type=int, default=16,
                       help="批次大小")
    parser.add_argument("--model", "-m", default="n",
                       choices=["n", "s", "m"],
                       help="模型大小: n(nano), s(small), m(medium)")
    parser.add_argument("--opset", "-o", type=int, default=12,
                       help="ONNX opset 版本 (預設 12)")
    parser.add_argument("--export-only", "-x", action="store_true",
                       help="僅導出現有模型")

    args = parser.parse_args()

    print_banner()

    if not check_requirements():
        sys.exit(1)

    if not prepare_data(args.data):
        sys.exit(1)

    yaml_path = create_yaml(args.data, args.classes, "yolov8_train")

    # 檢查是否已有訓練好的模型
    weights_path = Path("runs/train/jy_trainer/weights/best.pt")

    if args.export_only and weights_path.exists():
        best_model = weights_path
    else:
        best_model = train(yaml_path, args.model, args.epochs, args.batch)

    if not best_model.exists():
        print(f"\n[ERROR] 模型不存在: {best_model}")
        sys.exit(1)

    onnx_path = export_onnx(best_model, args.opset)
    copy_to_project(onnx_path)

if __name__ == "__main__":
    main()
